version: '3.8'

services:
  # Serviço PHP-FPM para a aplicação
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Serviço Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel

  # Serviço MySQL
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - laravel

  # Serviço Redis
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - laravel

  # Serviço para processamento de filas
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
